title: Bret Richards, Ph.D.
description: Assistant Professor of Management, Buena Vista University
theme: minima
minima:
  skin: classic

header_pages:
  - cv.md
  - research.md
  - teaching.md
  - service.md
